name: "Install uv and dependencies"
description: "uv installation followed by dependencies installation"
runs:
  using: "composite"
  steps:
    - name: Upgrade pip and install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv venv
        source .venv/bin/activate
        uv pip install